export function getTestData() {
  const tasks = [
    {
      serialNumber: 1,
      id: '1',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: true,
      answerOptions: [
        {
          id: '101',
          word: 'test option',
          wordPronounce: 'test option',
          wordType: 'OBJECT',
          audioFileUrl: '',
          pictureFileUrl: '',
          soundsCount: 0,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '101',
        word: 'test option',
        wordPronounce: 'test option',
        wordType: 'OBJECT',
        audioFileUrl: '',
        pictureFileUrl: '',
        soundsCount: 0,
        description: '',
        columnNumber: -1,
      },
    },
    {
      serialNumber: 2,
      id: '2',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: true,
      answerOptions: [
        {
          id: '102',
          word: '',
          wordPronounce: '',
          wordType: 'OBJECT',
          audioFileUrl: '',
          pictureFileUrl: '',
          soundsCount: 0,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '102',
        word: '',
        wordPronounce: '',
        wordType: 'OBJECT',
        audioFileUrl: '',
        pictureFileUrl: '',
        soundsCount: 0,
        description: '',
        columnNumber: -1,
      },
    },
    {
      serialNumber: 3,
      id: '3',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: true,
      answerOptions: [
        {
          id: '103',
          word: '',
          wordPronounce: '',
          wordType: 'OBJECT',
          audioFileUrl: '',
          pictureFileUrl: '',
          soundsCount: 0,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '103',
        word: '',
        wordPronounce: '',
        wordType: 'OBJECT',
        audioFileUrl: '',
        pictureFileUrl: '',
        soundsCount: 0,
        description: '',
        columnNumber: -1,
      },
    },
    {
      serialNumber: 4,
      id: '4',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: true,
      answerOptions: [
        {
          id: '104',
          word: '',
          wordPronounce: '',
          wordType: 'OBJECT',
          audioFileUrl: '',
          pictureFileUrl: '',
          soundsCount: 0,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '104',
        word: '',
        wordPronounce: '',
        wordType: 'OBJECT',
        audioFileUrl: '',
        pictureFileUrl: '',
        soundsCount: 0,
        description: '',
        columnNumber: -1,
      },
    },
  ];
  const exercises = [
    {
      seriesId: 1,
      id: '1',
      name: 'exercise 1',
      level: 1,
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['1'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
    {
      seriesId: 1,
      id: '2',
      name: 'exercise 1',
      level: 2,
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['2'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
    {
      seriesId: 1,
      id: '3',
      name: 'exercise 2',
      level: 1,
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['3'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
    {
      seriesId: 1,
      id: '4',
      name: 'exercise 2',
      level: 2,
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['4'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
  ];
  const series = [
    {
      id: '1',
      name: 'default',
      group: 1,
      type: 'SINGLE_SIMPLE_WORDS',
      level: 1,
      description: '',
      active: true,
      subGroups: [1, 2],
    },
  ];
  const groups = [
    { order: 1, id: '1', locale: 'ru-ru', name: 'default', description: '123', series: ['1'] },
  ];

  const subgroups = [
    {
      seriesId: '1',
      id: '1',
      level: 1,
      name: 'Семья',
      pictureUrl: 'pictures/theme/family.svg',
      description: 'Слова про семью',
      withPictures: false,
      exercises: ['1', '2', '3', '4'],
    },
    {
      seriesId: '1',
      id: '2',
      level: 2,
      name: 'Любимый дом',
      pictureUrl: 'pictures/theme/home.svg',
      description: 'Слова про дом',
      withPictures: false,
      exercises: [],
    },
  ];

  return {
    tasks,
    subgroups,
    exercises,
    series,
    groups,
    availableExercises: ['1', '3'],
  };
}
