#!/usr/bin/env node
"use strict";

process.title = "commit msg";

var commit_regex = /(EPMLABSBRN-[0-9]{1,4}|Merge|merge) .*/gi;

var fs = require("fs");
var cwd = process.cwd();
var path = require("path");
var commitMsg = fs
  .readFileSync(path.join(cwd, ".git", "COMMIT_EDITMSG"), "utf8")
  .trim();

if (!commit_regex.test(commitMsg)) {
  process.stderr.write("Aborting commit. Your commit message is missing valid header or description.\n");
  process.stderr.write("Use format 'EPMLABSBRN-# issue description' or 'Merge description'. Issue number must be in range [0-1999].\n");
  process.exit(1);
}
