#!/usr/bin/env node
"use strict";

process.title = "pre push";

function parseBranch(buf) {
  const match = /ref: refs\/heads\/([^\n]+)/.exec(buf.toString());
  return match ? match[1] : null;
}

var protected_branches = ["dev", "master"];
var fs = require("fs");
var cwd = process.cwd();
var path = require("path");
var branch = parseBranch(
  fs.readFileSync(path.join(cwd, ".git", "HEAD"), "utf8")
);

if (
  protected_branches.filter(function(name) {
    return name === branch;
  }).length
) {
  process.stderr.write(
    [
      "You are on branch $BRANCH. You a not supposed to push to this branch.",
      "Please use feature/bugfix branches."
    ].join("\n")
  );
  process.exit(1);
} else {
  process.exit(0);
}
