#!/bin/bash
master_branches=('origin/master' 'master' 'origin/dev' 'dev')
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for branch in "${master_branches[@]}"
do
    if [ $branch = $current_branch ]; then
        echo "You're about to commit to $branch and it's not allowed"
        exit 1
    fi
done
exit 0