ports:
  - port: 4200
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 8081
    onOpen: ignore
    visibility: private

image: gitpod/workspace-postgres

tasks:
  - init: ./gradlew clean bootJar -x test
    command: >
      export POSTGRES_DB=$PGDATABASE &&
      export POSTGRES_USER=gitpod &&
      java -jar build/libs/epam-brn.jar -Dspring.jpa.hibernate.ddl-auto=create
  - init: cd frontend && yarn install
    command: >
      export GITPODURLHOST=$(gp url 4200|cut -d\/ -f3) &&
      sed -i -e "s/_GITPODURLHOST_/$GITPODURLHOST/" .ember-cli &&
      yarn local
