ports:
  - port: 4200
    onOpen: open-preview
  - port: 5432
    onOpen: ignore

image: gitpod/workspace-postgres

tasks:
  - init: ./gradlew clean bootJar -x test
    command: java -jar build/libs/epam-brn.jar
  - init: cd frontend && yarn install
    command: yarn local
