ports:
  - port: 4200
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew clean bootJar -x test && java -jar build/libs/epam-brn.jar
  - init: cd frontend && yarn install && yarn local
