FROM node:12 as build-frontend
COPY frontend/ /src/
WORKDIR /src
RUN yarn
RUN node node_modules/ember-cli/bin/ember deploy production

FROM node:12 as build-frontend-angular
COPY frontend-angular/ /src/
WORKDIR /src
RUN npm ci
RUN npm run build

# Creates minimal image with proper TLS configs, will work only if target will be specified in docker build

FROM nginx:alpine AS alpine_with_tls
COPY default_with_tls.conf /etc/nginx/conf.d/default.conf
COPY --from=build-frontend /src/tmp/deploy-dist /usr/share/nginx/html/
COPY --from=build-frontend-angular /src/dist/frontend-angular /usr/share/nginx/html/admin/

# Does not break backward compatibility and uses standard config as earlier, so docker build will build usual image
# Hopefully it will not crash because of overwriting

FROM alpine_with_tls
COPY default.conf /etc/nginx/conf.d/
