kotlin.code.style=official

springBootVersion=3.5.3
springDependencyVersion=1.1.7
kotlinVersion=2.4.0
kotlinxCoroutinesCoreVersion=1.10.1
flywayVersion=11.8.2
junitVersion=5.12.2
mockkVersion=1.13.17
kotestAssertionsVersion=5.9.1
jsonVersion=20250107
log4jApiKotlinVersion=1.1.0
springCloudContractWiremockVersion=4.3.0
testContainersVersion=2.0.5
okhttp3Version=4.12.0
springDocOpenApiVersion=2.8.6

org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m