#%RAML 1.0
title: BRN API
version: v1
baseUri: http://localhost:8080
mediaType:
  - application/json

/groups:
  post:
  get:
    responses:
      200:
        body:
          example: !include samples/groups.json
  /{groupId}?include=series:
    get:
      responses:
        200:
          body:
            example: !include samples/group_inlclude_series.json
  /{groupId}:
    patch:
    get:
      responses:
        200:
          body:
            example: !include samples/group.json