export function getData() {
  const tasks = [
    {
      serialNumber: 1,
      id: '1',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: false,
      answerOptions: [
        {
          id: '4',
          audioFileUrl: '',
          word: 'вить',
          wordPronounce: 'вить',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '6',
          audioFileUrl: '',
          word: 'сад',
          wordPronounce: 'сад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '2',
          audioFileUrl: '',
          word: 'быль',
          wordPronounce: 'быль',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '5',
          audioFileUrl: '',
          word: 'бум',
          wordPronounce: 'бум',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '3',
          audioFileUrl: '',
          word: 'гад',
          wordPronounce: 'гад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '4',
        audioFileUrl: '',
        word: 'вить',
        wordPronounce: 'вить',
        wordType: 'OBJECT',
        pictureFileUrl:
          'https://klike.net/uploads/posts/2019-07/1564314090_3.jpg',
        soundsCount: 1,
        description: '',
        columnNumber: -1,
      },
    },
    {
      serialNumber: 2,
      id: '2',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: false,
      answerOptions: [
        {
          id: '4',
          audioFileUrl: '',
          word: 'вить',
          wordPronounce: 'вить',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '6',
          audioFileUrl: '',
          word: 'сад',
          wordPronounce: 'сад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '2',
          audioFileUrl: '',
          word: 'быль',
          wordPronounce: 'быль',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '5',
          audioFileUrl: '',
          word: 'бум',
          wordPronounce: 'бум',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '3',
          audioFileUrl: '',
          word: 'гад',
          wordPronounce: 'гад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '4',
        audioFileUrl: '',
        word: 'вить',
        wordPronounce: 'вить',
        wordType: 'OBJECT',
        pictureFileUrl:
          'https://klike.net/uploads/posts/2019-07/1564314090_3.jpg',
        soundsCount: 1,
        description: '',
        columnNumber: -1,
      },
    },
    {
      serialNumber: 3,
      id: '3',
      name: 'default',
      level: 0,
      exerciseType: 'SINGLE_SIMPLE_WORDS',
      exerciseMechanism: 'WORDS',
      shouldBeWithPictures: false,
      answerOptions: [
        {
          id: '4',
          audioFileUrl: '',
          word: 'вить',
          wordPronounce: 'вить',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '6',
          audioFileUrl: '',
          word: 'сад',
          wordPronounce: 'сад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '2',
          audioFileUrl: '',
          word: 'быль',
          wordPronounce: 'быль',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '5',
          audioFileUrl: '',
          word: 'бум',
          wordPronounce: 'бум',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
        {
          id: '3',
          audioFileUrl: '',
          word: 'гад',
          wordPronounce: 'гад',
          wordType: 'OBJECT',
          pictureFileUrl: '',
          soundsCount: 1,
          description: '',
          columnNumber: -1,
        },
      ],
      correctAnswer: {
        id: '4',
        audioFileUrl: '',
        word: 'вить',
        wordPronounce: 'вить',
        wordType: 'OBJECT',
        pictureFileUrl:
          'https://klike.net/uploads/posts/2019-07/1564314090_3.jpg',
        soundsCount: 1,
        description: '',
        columnNumber: -1,
      },
    },
  ];
  const exercises = [
    {
      seriesId: 1,
      id: '1',
      name: 'default',
      level: 1,
      exerciseMechanism: 'WORDS',
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['1', '2'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
    {
      seriesId: 1,
      id: '2',
      name: 'default',
      level: 2,
      exerciseMechanism: 'WORDS',
      noise: { level: 0, url: null },
      template: '',
      available: true,
      tasks: tasks.filter((t) => ['3'].includes(t.id)),
      signals: [],
      active: true,
      changedBy: 'InitialDataLoader',
      changedWhen: '2021-11-05T18:00:00',
      isAudioFileUrlGenerated: false,
      playWordsCount: 1,
      wordsColumns: 3,
    },
  ];
  const series = [
    {
      id: '1',
      name: 'default',
      group: 1,
      type: 'SINGLE_SIMPLE_WORDS',
      level: 1,
      description: '',
      active: true,
      subGroups: [],
    },
  ];
  const groups = [
    { order: 1, id: '1', locale: 'ru-ru', name: 'default', description: '123', series: ['1'] },
  ];

  const subgroups = [
    {
      seriesId: '1',
      id: '1',
      level: 1,
      name: 'Семья',
      pictureUrl: 'pictures/theme/family.svg',
      description: 'Слова про семью',
      withPictures: false,
      exercises: ['1', '2'],
    },
    {
      seriesId: '1',
      id: '2',
      level: 2,
      name: 'Любимый дом',
      pictureUrl: 'pictures/theme/home.svg',
      description: 'Слова про дом',
      withPictures: false,
      exercises: [],
    },
  ];
  return { tasks, subgroups, exercises, series, groups };
}
