package com.epam.brn.service

import com.epam.brn.config.ExcludeFromJacocoGeneratedReport
import com.epam.brn.dto.AudioFileMetaData
import com.epam.brn.dto.YandexIamTokenDto
import com.epam.brn.dto.yandex.tts.ContainerAudio
import com.epam.brn.dto.yandex.tts.Hint
import com.epam.brn.dto.yandex.tts.OutputAudioSpec
import com.epam.brn.dto.yandex.tts.YandexTtsRequest
import com.epam.brn.dto.yandex.tts.YandexTtsResponse
import com.epam.brn.enums.BrnLocale
import com.epam.brn.exception.YandexServiceException
import com.epam.brn.service.yandex.tts.config.YandexTtsProperties
import org.apache.logging.log4j.kotlin.logger
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.web.reactive.function.client.WebClient
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.time.ZonedDateTime
import java.util.Base64

@Service
@ConditionalOnProperty(name = ["default.tts.provider"], havingValue = "yandex")
class YandexSpeechKitService(
    private val wordsService: WordsService,
    private val timeService: TimeService,
    private val yandexTtsProperties: YandexTtsProperties,
    @Qualifier("yandexTtsWebClient") private val yandexTtsWebClient: WebClient,
    @Qualifier("yandexIamTokenWebClient") private val yandexIamTokenWebClient: WebClient,
) : TextToSpeechService {
    var iamToken: String = ""
    var iamTokenExpiresTime: LocalDateTime = LocalDateTime.now(ZoneOffset.UTC)

    private val log = logger()

    fun getYandexIamTokenForAudioGeneration(): String {
        if (iamToken.isNotEmpty() && iamTokenExpiresTime.isAfter(timeService.now()))
            return iamToken
        val tokenDto = requestIamToken()
        iamToken = tokenDto.iamToken
        iamTokenExpiresTime =
            ZonedDateTime
                .parse(tokenDto.expiresAt)
                .withZoneSameInstant(ZoneOffset.UTC)
                .toLocalDateTime()
        log.info("Got IAM token from Yandex Cloud, expires at ${tokenDto.expiresAt}")
        return iamToken
    }

    private fun requestIamToken(): YandexIamTokenDto = yandexIamTokenWebClient
        .post()
        .bodyValue(mapOf("yandexPassportOauthToken" to yandexTtsProperties.authToken))
        .retrieve()
        .onStatus(HttpStatus::isError) { response ->
            response
                .bodyToMono(String::class.java)
                .defaultIfEmpty("no body")
                .map { body -> YandexServiceException("Can't get Yandex IAM token, status=${response.statusCode()}: $body") }
        }.bodyToMono(YandexIamTokenDto::class.java)
        .block() ?: throw YandexServiceException("Failed to get IAM token from Yandex Cloud")

    fun generateAudioStream(audioFileMetaData: AudioFileMetaData): InputStream {
        val token = getYandexIamTokenForAudioGeneration()
        val emotion = yandexTtsProperties.emotions.first()

        val request =
            YandexTtsRequest(
                text = audioFileMetaData.text,
                outputAudioSpec = OutputAudioSpec(containerAudio = ContainerAudio()),
                hints =
                    listOf(
                        Hint(voice = audioFileMetaData.voice.lowercase()),
                        Hint(speed = audioFileMetaData.speedFloat),
                        Hint(role = emotion),
                    ),
            )

        val responseBody = requestAudioSynthesis(token, request)

        val outputStream = ByteArrayOutputStream()
        parseAudioChunks(responseBody).forEach { outputStream.write(it) }
        val audioBytes = outputStream.toByteArray()

        if (audioBytes.isEmpty())
            throw YandexServiceException("Yandex Cloud returned empty audio for $audioFileMetaData")

        log.info("Ogg audio file for $audioFileMetaData was successfully generated by Yandex!")
        return ByteArrayInputStream(audioBytes)
    }

    @ExcludeFromJacocoGeneratedReport
    private fun requestAudioSynthesis(
        token: String,
        request: YandexTtsRequest,
    ): String = yandexTtsWebClient
        .post()
        .header("Authorization", "Bearer $token")
        .header("x-folder-id", yandexTtsProperties.folderId)
        .bodyValue(request)
        .retrieve()
        .onStatus(HttpStatus::isError) { response ->
            response
                .bodyToMono(String::class.java)
                .defaultIfEmpty("no body")
                .map { body -> YandexServiceException("Yandex TTS error ${response.statusCode()}: $body") }
        }.bodyToMono(String::class.java)
        .block() ?: throw YandexServiceException("Yandex Cloud did not return audio response")

    internal fun parseAudioChunks(responseBody: String): List<ByteArray> {
        val mapper =
            ObjectMapper()
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        return responseBody
            .lines()
            .filter { it.isNotBlank() }
            .mapNotNull { line ->
                val response = mapper.readValue(line, YandexTtsResponse::class.java)
                response.result
                    ?.audioChunk
                    ?.data
                    ?.let { Base64.getDecoder().decode(it) }
            }
    }

    fun validateLocaleAndVoice(
        locale: String,
        voice: String,
    ) {
        if (!BrnLocale.values().map { it.locale }.contains(locale.lowercase()))
            throw IllegalArgumentException("Locale $locale does not support yet for generation audio files.")
        val localeVoices = wordsService.getVoicesForLocale(locale)
        if (voice.isNotEmpty() && !localeVoices.contains(voice))
            throw IllegalArgumentException("Locale $locale does not support voice $voice, only $localeVoices.")
    }

    override fun generateAudioOggStreamWithValidation(audioFileMetaData: AudioFileMetaData): InputStream {
        validateLocaleAndVoice(audioFileMetaData.locale, audioFileMetaData.voice)
        return generateAudioStream(
            AudioFileMetaData(
                audioFileMetaData.text,
                audioFileMetaData.locale,
                audioFileMetaData.voice.ifEmpty { wordsService.getDefaultWomanVoiceForLocale(audioFileMetaData.locale) },
                audioFileMetaData.speedFloat,
            ),
        )
    }
}
