package com.epam.brn.enums

enum class ExerciseType {
    WORDS_SEQUENCES,
    SENTENCE,
    SINGLE_SIMPLE_WORDS,
    PHRASES,
    TWO_DIFFERENT_LENGTH_SIGNAL,
    TWO_DIFFERENT_FREQUENCY_SIGNAL,
    THREE_DIFFERENT_LENGTH_SIGNAL,
    THREE_DIFFERENT_FREQUENCY_SIGNAL;
}
