package com.epam.brn.enums

enum class ExerciseType {
    WORDS_SEQUENCES,
    SENTENCE,
    SINGLE_SIMPLE_WORDS,
    SINGLE_WORDS_KOROLEVA,
    PHRASES,
    FREQUENCY_WORDS,
    DI,
    DURATION_SIGNALS,
    FREQUENCY_SIGNALS,
    SYLLABLES_KOROLEVA;
}
