#!/usr/bin/env node

/**
 * Phase 3b: Schema Index Generator
 *
 * Standalone Node.js script (not a jscodeshift per-file transform).
 * Reads the schemas directory and generates a barrel file that collects
 * all schemas and extensions.
 *
 * Usage:
 *   tsx src/phase-3b-schema-index.ts --schemasDir=path/to/app/schemas
 */

import * as fs from 'fs';
import * as path from 'path';

export interface SchemaExport {
  filePath: string;
  relativePath: string;
  schemas: string[];
  extensions: string[];
}

function main(): void {
  const args = process.argv.slice(2);
  let schemasDir = '';
  let dryRun = false;

  for (const arg of args) {
    if (arg.startsWith('--schemasDir=')) {
      schemasDir = arg.slice('--schemasDir='.length);
    } else if (arg === '--dryRun' || arg === '--dry-run') {
      dryRun = true;
    }
  }

  if (!schemasDir) {
    console.error('Usage: phase-3b-schema-index.ts --schemasDir=path/to/app/schemas');
    process.exit(1);
  }

  const resolvedDir = path.resolve(schemasDir);
  if (!fs.existsSync(resolvedDir)) {
    console.error(`Schemas directory not found: ${resolvedDir}`);
    process.exit(1);
  }

  const exports = scanSchemas(resolvedDir);
  const output = generateBarrelFile(exports);

  const indexPath = path.join(resolvedDir, 'index.ts');
  if (dryRun) {
    console.log(`[dry-run] Would write ${indexPath}:`);
    console.log(output);
  } else {
    fs.writeFileSync(indexPath, output, 'utf-8');
    console.log(`Generated ${indexPath}`);
  }
  console.log(
    `  ${exports.reduce((n, e) => n + e.schemas.length, 0)} schemas, ` +
      `${exports.reduce((n, e) => n + e.extensions.length, 0)} extensions`,
  );
}

/**
 * Scan the schemas directory for *Schema and *Extension exports.
 * Convention: schemas are `export const XxxSchema` and extensions are `export const XxxExtension`.
 */
export function scanSchemas(schemasDir: string): SchemaExport[] {
  const results: SchemaExport[] = [];
  const files = walkDir(schemasDir);

  for (const filePath of files) {
    const basename = path.basename(filePath);
    // Skip index.ts itself
    if (basename === 'index.ts') continue;
    // Only .ts and .gts files
    if (!filePath.endsWith('.ts') && !filePath.endsWith('.gts')) continue;

    const content = fs.readFileSync(filePath, 'utf-8');
    const schemas: string[] = [];
    const extensions: string[] = [];

    // Strip commented-out lines to avoid false matches
    const filteredContent = stripCommentLines(content);

    // Find exported const *Schema
    const schemaMatches = filteredContent.matchAll(
      /export\s+const\s+(\w+Schema)\b/g,
    );
    for (const match of schemaMatches) {
      schemas.push(match[1]);
    }

    // Find exported const *Extension
    const extensionMatches = filteredContent.matchAll(
      /export\s+const\s+(\w+Extension)\b/g,
    );
    for (const match of extensionMatches) {
      extensions.push(match[1]);
    }

    if (schemas.length > 0 || extensions.length > 0) {
      const relativePath =
        './' +
        path
          .relative(schemasDir, filePath)
          .replace(/\.(g?ts)$/, '')
          .replace(/\\/g, '/');

      results.push({ filePath, relativePath, schemas, extensions });
    }
  }

  // Sort by relative path for deterministic output
  results.sort((a, b) => a.relativePath.localeCompare(b.relativePath));

  return results;
}

/**
 * Generate the barrel file content.
 */
export function generateBarrelFile(exports: SchemaExport[]): string {
  const lines: string[] = [];

  // Auto-generated header comment
  lines.push('// This file is auto-generated by phase-3b-schema-index.ts. Do not edit manually.');
  lines.push('');

  // Imports
  for (const exp of exports) {
    const allNames = [...exp.schemas, ...exp.extensions];
    lines.push(`import { ${allNames.join(', ')} } from '${exp.relativePath}';`);
  }

  lines.push('');

  // ALL_SCHEMAS array
  const allSchemas = exports.flatMap((e) => e.schemas);
  lines.push(`export const ALL_SCHEMAS = [`);
  for (const schema of allSchemas) {
    lines.push(`  ${schema},`);
  }
  lines.push(`];`);

  lines.push('');

  // ALL_EXTENSIONS array
  const allExtensions = exports.flatMap((e) => e.extensions);
  if (allExtensions.length > 0) {
    lines.push(`export const ALL_EXTENSIONS = [`);
    for (const ext of allExtensions) {
      lines.push(`  ${ext},`);
    }
    lines.push(`];`);
  } else {
    lines.push(`export const ALL_EXTENSIONS: never[] = [];`);
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Strip single-line comments (//) and block comments to avoid
 * regex matching commented-out export statements.
 */
function stripCommentLines(source: string): string {
  const lines = source.split('\n');
  const filtered: string[] = [];
  let inBlockComment = false;

  for (const line of lines) {
    if (inBlockComment) {
      if (line.includes('*/')) {
        inBlockComment = false;
      }
      continue;
    }
    const trimmed = line.trimStart();
    if (trimmed.startsWith('//')) {
      continue;
    }
    if (trimmed.startsWith('/*')) {
      if (!trimmed.includes('*/')) {
        inBlockComment = true;
      }
      continue;
    }
    filtered.push(line);
  }

  return filtered.join('\n');
}

/**
 * Recursively walk a directory and return all file paths.
 */
function walkDir(dir: string): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath));
    } else {
      results.push(fullPath);
    }
  }
  return results;
}

if (require.main === module) {
  main();
}
