package com.epam.brn.constant

enum class WordTypeEnum {
    OBJECT,
    OBJECTS,
    OBJECT_ACTION,
    OBJECTS_ACTION,
    OBJECT_DESCRIPTION,
    OBJECTS_DESCRIPTION,
    ADDITION_OBJECT,
    ADDITION_OBJECT_DESCRIPTION,
    COUNT
}