#%RAML 1.0
title: BRN API
version: v1
baseUri: http://localhost:8080/api
mediaType:
  - application/json

# GROUP ----------------------------

/groups:
  get:
    responses:
      200:
        body:
          example: !include samples/groups.json
  /{groupId}:
    get:
      responses:
        200:
          body:
            example: !include samples/group.json

# SERIES ----------------------------

/series:
  get:
    queryParameters:
      groupId:
        description: "ID of the group series belongs to"
        required: true
        type: string
        example: "42"
    responses:
      200:
        body:
          example: !include samples/series_by_group.json
  /{seriesId}:
    get:
      responses:
        200:
          body:
            example: !include samples/series.json

# EXERCISE ----------------------------

/exercises:
  get:
    queryParameters:
      seriesId:
        description: "ID of the series exercises belongs to"
        required: true
        type: string
        example: "42"
      userId:
        description: "ID of the user for which we want to get done exercises"
        required: false
        type: string
        example: "42"
    responses:
      200:
        body:
          example: !include samples/exercises.json
  /{exerciseId}:
    get:
      responses:
        200:
          body:
            example1: !include samples/exercise_for_single_words_series.json
            example2: !include samples/exercise_for_sequence_words_series.json
# TASK ----------------------------

/tasks:
  get:
    description: |
    The tasks endpoint returns tasks assotiated with specified exercise id
    queryParameters:
      exerciseId:
        description: "ID of the exercise tasks belongs to"
        required: true
        type: string
        example: "3"
    responses:
      200:
        body:
          application/json:
            example_for_single_words_series: !include samples/tasks_by_exercise_for_single_words_series.json
            example_for_words_sequences_serias: !include samples/tasks_by_exercise_for_words_sequences_serias.json
  /{taskId}:
    get:
      description: Get a task by id
      responses:
        200:
          body:
            application/json:
              example_for_single_words_series: !include samples/task_by_id_for_single_words_series.json
              example_for_words_sequences_serias: !include samples/task_by_id_for_words_sequences_serias.json


# STUDY_HISTORY ----------------------
/study-history:
  post:
  description: Save history of exercises done by user
    body:
      application/json:
        example: !include samples/study_history.json
    responses:
      201:
        example: !include samples/study_history_response.json.json

# LOAD FILES ----------------------
/admin/loadFile:
  post:
    body:
      multipart/form-data:
        properties:
          taskFile:
            description: "File with tasks to be uploaded"
            format: "exerciseId orderNumber word audioFileName pictureFileName words wordType
                     1 1 бал no_noise/бал.mp3 pictures/бал.jpg (бам,сам,дам,зал,бак) OBJECT"
            required: true
            type: file
    responses:
      201:

/admin/loadTasksFile:
  post:
    body:
      multipart/form-data:
        properties:
          seriesId:
            description: "ID of the series created exercises belongs to"
            required: true
            type: string
            example: "42"
          taskFile:
            description: "File with tasks to be uploaded"
            formatForSeries1: "orderNumber word audioFileName pictureFileName words wordType
                               1 бал no_noise/бал.mp3 pictures/бал.jpg (бам,сам,дам,зал,бак) OBJECT"
            formatForSeries2: "orderNumber words
                               1 [(),(),(мальчик, девочка), (сидит, слушает),(),()]"
            required: true
            type: file
    responses:
      201: