CREATE TABLE IF NOT EXISTS notification
(
    id bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT notification_pkey PRIMARY KEY,
    user_id              BIGINT REFERENCES user_account (id),
    text                 VARCHAR(255) NOT NULL,
    scheduled_date       TIMESTAMP NOT NULL,
    checked              BOOLEAN NOT NULL
);