
create table user_analytics
(
    id             bigint generated by default as identity
        primary key,
    done_exercises integer,
    first_done     timestamp,
    last_done      timestamp,
    role_name      varchar(255),
    spent_time     bigint,
    study_days     integer,
    user_id        bigint
);

create index user_analytics_ix_role_name
    on user_analytics (role_name);

