-- #2609 Precomputed user analytics store.
-- A nightly job appends one row per user per day (snapshot_date), so the table
-- keeps a daily history of aggregates and can back non-realtime analytics /
-- trend reports without re-aggregating study_history on every request.
-- The live /admin/users endpoint is NOT served from here (it stays realtime, see #2971).

create table user_analytics
(
    id             bigint generated by default as identity primary key,
    snapshot_date  date      not null,
    user_id        bigint    not null,
    role_name      varchar(255) not null,
    first_done     timestamp,
    last_done      timestamp,
    spent_time     bigint,
    done_exercises integer,
    study_days     integer,
    constraint user_analytics_uq_user_role_date unique (user_id, role_name, snapshot_date)
);

create index user_analytics_ix_snapshot_date on user_analytics (snapshot_date);
create index user_analytics_ix_role_name on user_analytics (role_name);
