create table if not exists github_user
(
    id              bigint primary key,
    login           varchar(255) not null,
    email           varchar(255),
    name            varchar(255),
    avatar_url      varchar(255),
    bio             varchar(255),
    company         varchar(255),
    contributions   bigint
);

create table if not exists contributor
(
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    description     varchar(255),
    company         varchar(255),
    name_en         varchar(255),
    description_en  varchar(255),
    company_en      varchar(255),
    type            varchar(255),
    picture_url     varchar(255),
    contribution    bigint,
    active          bool NOT NULL DEFAULT false,
    github_id       bigint REFERENCES github_user(id)
);

create table if not exists contact
(
    id              bigint generated by default as identity primary key,
    type            varchar(50),
    value           varchar(255),
    contributor_id  bigint REFERENCES contributor(id)
);
