create table if not exists azure_voice_info
(
    id                bigint generated by default as identity
        primary key,
    display_name      varchar(255) not null,
    gender            varchar(255) not null,
    local_name        varchar(255),
    locale            varchar(255) not null,
    locale_name       varchar(255),
    name              varchar(255) not null,
    sample_rate_hertz varchar(255),
    short_name        varchar(255) not null,
    status            varchar(255),
    voice_type        varchar(255)
);

create table if not exists azure_speech_style
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

create table if not exists azure_voice_style
(
    style_id bigint not null
        constraint fkcqmx5littrwxj8pdsof220lqo
            references azure_voice_info,
    voice_id bigint not null
        constraint fkiyv3uy78yki8w38qtu3ghkhqc
            references azure_speech_style,
    primary key (style_id, voice_id)
);
