insert into contributor (name, description, company, name_en, description_en, company_en, type, picture_url,
                         contribution, active, github_id)
values
    ('Королева Инна Васильевна',
     'Научный руководитель реабилитационного отделения, доктор психологических наук, профессор, автор серии ' ||
     'методических пособий "Учусь слушать и говорить"',
     null,
     'Inna Koroleva',
     'Academic supervisor of the rehabilitation department, Doctor of Psychology, Professor, author of the manuals ' ||
     '"Learning to listen and speak"',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/koroleva.png',
     0, true, null),
    ('Гарбарук Екатерина Сергеевна',
     'Кандидат биологических наук, специалист Лаборатории слуха и речи ПСПбГМУ, специалист в области диагностики ' ||
     'слуховых нарушений',
     null,
     'Ekaterina Garbaruk',
     'Candidate of Biological Sciences, expert at the Laboratory of Hearing and Speech (The Pavlov First Saint ' ||
     'Petersburg State Medical University), expert in diagnosis of aural disorders',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/garbaruk.png',
     0, true, null),
    ('Прошина Любовь Александровна',
     'Сурдопедагог, РНПЦ оториноларингологии, опыт работы более 10 лет',
     null,
     'Lubov Proshina',
     'Teacher of the deaf, Belarusian Republican Scientific and Practical Center of Otorhinolaryngology, 10+ years ' ||
     'of experience',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/proshina.png',
     0, true, null),
    ('Метельская Наталья Николаевна',
     'Сурдопедагог, УЗ Могилевская областная детская больница, опыт работы более 20 лет',
     null,
     'Natalia Metelskaya',
     'Teacher of the deaf, Mogilev Regional Children''s Hospital (Belarus), 20+ years of experience',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/metelskaya.png',
     0, true, null),
    ('Березкина Ксения Сергеевна',
     'Сурдопедагог, Городской ресурсный центр для детей с нарушением слуха, опыт работы более 10 лет',
     null,
     'Ksenia Berezkina',
     'Teacher of the deaf, City Resource Center for Hearing Impaired Children, 10+ years of experience',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/berezkina.png',
     0, true, null),
    ('Сивенкова Кристина Александровна',
     'Сурдопедагог, СПб Сурдоцентр, молодой специалист',
     null,
     'Kristina Sivenkova',
     'Teacher of the deaf, Saint Petersburg Center of Otorhinolaryngology, young professional',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/sivenkova.png',
     0, true, null),
    ('Платоненко Дарья Сергеевна',
     'Сурдопедагог, РНПЦ оториноларингологии, опыт работы более 3 лет',
     null,
     'Daria Platonenko',
     'Teacher of the deaf, Belarusian Republican Scientific and Practical Center of Otorhinolaryngology, 3+ years ' ||
     'of experience',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/platonenko.png',
     0, true, null),
    ('Сухова Ольга',
     'Сурдопедагог, дефектолог, автор пособий "Слушать интересно"',
     null,
     'Olga Sukhova',
     'Teacher of the deaf, defectologist, author of the manuals "It is interesting to listen"',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/sukhova.png',
     0, true, null),
    ('Юлия Кибалова',
     'Сурдопедагог, дефектолог, Лаборатория слуха и речи ПСПбГМУ, опыт работы более 10 лет',
     null,
     'Yulia Kibalova',
     'Teacher of the deaf, defectologist, expert at the Laboratory of Hearing and Speech (The Pavlov First Saint ' ||
     'Petersburg State Medical University), 10+ years of experience',
     null,
     'SPECIALIST',
     'https://brnup.s3.eu-north-1.amazonaws.com/pictures/specialists/kibalova.png',
     0, true, null)


