create table if not exists audiometry
(
    id              bigint generated by default as identity
        constraint audiometry_pkey
            primary key,
    audiometry_type varchar(255) not null
        constraint uk_qj91muatrl57066evekdaxn9j
            unique,
    description     varchar(255),
    name            varchar(255) not null
        constraint uk_o7gaukdmfpy03upcpw6m35io4
            unique
);

create table if not exists audiometry_task
(
    id               bigint generated by default as identity
        constraint audiometry_task_pkey
            primary key,
    audiometry_group varchar(255),
    count            integer not null,
    frequency_zone   varchar(255),
    level            integer,
    max_frequency    integer,
    min_frequency    integer,
    show_size        integer not null,
    audiometry_id    bigint
        constraint fkills0mbh51bwkrffaaowqe4vs
            references audiometry,
    constraint uka601vt31nr5yjah9wo7e8qcyg
        unique (audiometry_group, frequency_zone)
);

create table if not exists audiometry_history
(
    id                  bigint generated by default as identity
        constraint audiometry_history_pkey
            primary key,
    end_time            timestamp,
    execution_seconds   integer,
    repetition_index    real,
    replays_count       integer,
    right_answers       integer  not null,
    right_answers_index real,
    start_time          timestamp,
    tasks_count         smallint not null,
    audiometry_task_id  bigint
        constraint fkkwhgr47w5tomfuq2vsnwg603m
            references audiometry_task,
    user_id             bigint
        constraint fk39m3gvi6no67v7b0x17phiuxy
            references user_account,
    constraint ukekiuxjh0lvrl6mdkwifwskq5v
        unique (user_id, audiometry_task_id, start_time)
);