UPDATE series SET description = 'Распознавание похожих фраз' WHERE description = 'Распознование похожих фраз';
UPDATE series SET description = 'Распознавание сигналов по длительности' WHERE description = 'Распознование сигналов по длительности';
UPDATE series SET description = 'Распознавание сигналов по частоте сигналов' WHERE description = 'Распознование сигналов по частоте сигналов';
UPDATE sub_group SET description = 'Слова о школе и учёбе' WHERE description = 'Слова о школе и учебе';
UPDATE sub_group SET description = 'Математика и её термины' WHERE description = 'Математика и ее термины';
UPDATE sub_group SET description = 'цвета' WHERE description = 'цета';
UPDATE sub_group SET description = 'развлечений' WHERE description = 'развлеченийи';
UPDATE resource SET word='Фургон несётся' WHERE word = 'Фургон несется';
UPDATE resource SET word='Фургон несётся по скоростной магистрали' WHERE word = 'Фургон несется по скоростной магистрали';
UPDATE resource SET word='Слон везёт старого погонщика' WHERE word = 'Слон везет старого погонщика';
UPDATE resource SET word='Почтальон принёс' WHERE word = 'Почтальон принес';
UPDATE resource SET word='Почтальон принёс письмо домой' WHERE word = 'Почтальон принес письмо домой';
UPDATE resource SET word='Пьёт чай с лимоном' WHERE word = 'Пьет чай с лимоном';
UPDATE resource SET word='Мама шьёт платье' WHERE word = 'Мама шьет платье';
UPDATE resource SET word='Мама не шьёт платье' WHERE word = 'Мама не шьет платье';
UPDATE resource SET word='Лесник нашёл гриб' WHERE word = 'Лесник нашел гриб';
UPDATE resource SET word='Лесник нашёл грибы' WHERE word = 'Лесник нашел грибы';
UPDATE resource SET word='Папа принёс шар' WHERE word = 'Папа принес шар';
UPDATE resource SET word='Папа принёс шары' WHERE word = 'Папа принес шары';
UPDATE resource SET word='На улице идёт солдат' WHERE word = 'На улице идет солдат';
UPDATE resource SET word='Котёнок сидит в коробке' WHERE word = 'Котенок сидит в коробке';
UPDATE resource SET word='Котёнок сидит на коробке' WHERE word = 'Котенок сидит на коробке';
UPDATE resource SET word='идёт' WHERE word = 'идет';
UPDATE resource SET word='загорает' WHERE word = 'загарает';
UPDATE resource SET word='волчонка' WHERE word = 'волчёнка';
UPDATE resource SET word='мяукают' WHERE word = 'маукают';
UPDATE resource SET word='топочут' WHERE word = 'топочат';
UPDATE resource SET word='мурлычут' WHERE word = 'мурлычат';
UPDATE resource SET word='чёрные' WHERE word = 'черные';
UPDATE resource SET word='барсуки' WHERE word = 'борсуки';
UPDATE resource SET word='лётчик' WHERE word = 'летчик';
UPDATE resource SET word='села' WHERE word = 'сла';
UPDATE resource SET word='мотылёк' WHERE word = 'мотылек';
UPDATE resource SET word='вёдер' WHERE word = 'ведер';
UPDATE resource SET word='пьёт' WHERE word = 'пьет';
UPDATE resource SET word='чёрную' WHERE word = 'черную';
UPDATE resource SET word='лёгкую' WHERE word = 'легкую';
UPDATE resource SET word='жёлтых' WHERE word = 'желтых';
UPDATE resource SET word='тёмные' WHERE word = 'темные';
UPDATE resource SET word='твёрдые' WHERE word = 'твердые';
UPDATE resource SET word='лёгких' WHERE word = 'легких';
UPDATE resource SET word='расчёсывают' WHERE word = 'расчесывают';
UPDATE resource SET word='жёлтые' WHERE word = 'желтые';
UPDATE resource SET word='ёлки' WHERE word = 'елки';
UPDATE resource SET word='свёкор' WHERE word = 'свёкр';
UPDATE resource SET word='крёстная' WHERE word = 'крестная';
UPDATE resource SET word='новорождённый' WHERE word = 'новорожденный';
UPDATE resource SET word='матрас' WHERE word = 'матрац';
UPDATE resource SET word='легинсы' WHERE word = 'леггинсы';
UPDATE resource SET word='дублёнка' WHERE word = 'дубленка';
UPDATE resource SET word='хорёк' WHERE word = 'хорек';
UPDATE resource SET word='шиншилла' WHERE word = 'шиншила';
UPDATE resource SET word='короткошёрстная' WHERE word = 'короткошерстная';
UPDATE resource SET word='длинношерстная' WHERE word = 'длинношёрстная';
UPDATE resource SET word='контролёр' WHERE word = 'контролер';
UPDATE resource SET word='четырёхугольник' WHERE word = 'четырехугольник';
UPDATE resource SET word='костёл' WHERE word = 'костел';
UPDATE resource SET word='перекрёсток' WHERE word = 'перекресток';
UPDATE resource SET word='лифтёр' WHERE word = 'лифтер';
UPDATE resource SET word='актёр' WHERE word = 'актер';
UPDATE resource SET word='режиссёр' WHERE word = 'режиссер';
UPDATE resource SET word='лёгкие' WHERE word = 'легкие';
UPDATE resource SET word='листовёртка' WHERE word = 'листовертка';
UPDATE resource SET word='дирижёр' WHERE word = 'дирижер';
UPDATE resource SET word='берёт' WHERE word = 'берет';
UPDATE resource SET word='плывёт' WHERE word = 'плывет';
UPDATE resource SET word='самолёт' WHERE word = 'самолет';
UPDATE resource SET word='вертолёт' WHERE word = 'вертолет';
UPDATE resource SET word='ламборгини' WHERE word = 'ламборджини';
UPDATE resource SET word='фуникулёр' WHERE word = 'фуникулер';
UPDATE resource SET word='черёмуха' WHERE word = 'черемуха';
UPDATE resource SET word='тёрн' WHERE word = 'терн';
UPDATE resource SET word='лён' WHERE word = 'лен';
UPDATE resource SET word='клён' WHERE word = 'клен';
UPDATE resource SET word='берёза' WHERE word = 'береза';
UPDATE resource SET word='тис' WHERE word = 'тисс';
UPDATE resource SET word='сикомор' WHERE word = 'сикамор';
UPDATE resource SET word='сёрфинг' WHERE word = 'серфинг';
UPDATE resource SET word='кёрлинг' WHERE word = 'керлинг';
UPDATE resource SET word='виндсёрфинг' WHERE word = 'виндсерфинг';
UPDATE resource SET word='боксёр' WHERE word = 'боксер';
UPDATE resource SET word='василёк' WHERE word = 'василек';
UPDATE resource SET word='верёвка' WHERE word = 'веревка';
UPDATE resource SET word='отвёртка' WHERE word = 'отвертка';
