import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync } from 'child_process';
import { scanSchemas, generateBarrelFile } from '../src/phase-3b-schema-index';

const scriptPath = path.resolve(__dirname, '../src/phase-3b-schema-index.ts');

function createTempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'phase-3b-test-'));
}

function runScript(schemasDir: string): string {
  return execSync(`npx tsx "${scriptPath}" --schemasDir="${schemasDir}"`, {
    encoding: 'utf-8',
    cwd: path.resolve(__dirname, '..'),
  });
}

describe('Phase 3b: Schema Index Generator', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should generate barrel file with schemas and extensions', () => {
    // Create mock schema files
    fs.writeFileSync(
      path.join(tempDir, 'foo.ts'),
      `export const FooSchema = withDefaults({ type: 'foo', fields: [] });
export const FooExtension: Extension = { kind: 'object', name: 'foo-ext', features: {} };
`,
      'utf-8',
    );

    fs.writeFileSync(
      path.join(tempDir, 'bar.ts'),
      `export const BarSchema = withDefaults({ type: 'bar', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const indexPath = path.join(tempDir, 'index.ts');
    expect(fs.existsSync(indexPath)).toBe(true);

    const output = fs.readFileSync(indexPath, 'utf-8');

    // Should import from both files
    expect(output).toContain("import { BarSchema } from './bar';");
    expect(output).toContain("import { FooSchema, FooExtension } from './foo';");

    // Should have ALL_SCHEMAS array with both schemas
    expect(output).toContain('export const ALL_SCHEMAS = [');
    expect(output).toContain('  BarSchema,');
    expect(output).toContain('  FooSchema,');

    // Should have ALL_EXTENSIONS array with the extension
    expect(output).toContain('export const ALL_EXTENSIONS = [');
    expect(output).toContain('  FooExtension,');
  });

  it('should include auto-generated header comment', () => {
    fs.writeFileSync(
      path.join(tempDir, 'foo.ts'),
      `export const FooSchema = withDefaults({ type: 'foo', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    expect(output.startsWith('// This file is auto-generated by phase-3b-schema-index.ts. Do not edit manually.')).toBe(true);
  });

  it('should handle nested schema directories', () => {
    const subDir = path.join(tempDir, 'task');
    fs.mkdirSync(subDir, { recursive: true });

    fs.writeFileSync(
      path.join(subDir, 'signal.ts'),
      `export const TaskSignalSchema = withDefaults({ type: 'task/signal', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    expect(output).toContain("import { TaskSignalSchema } from './task/signal';");
    expect(output).toContain('  TaskSignalSchema,');
  });

  it('should produce empty ALL_EXTENSIONS when no extensions exist', () => {
    fs.writeFileSync(
      path.join(tempDir, 'simple.ts'),
      `export const SimpleSchema = withDefaults({ type: 'simple', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    expect(output).toContain('export const ALL_EXTENSIONS: never[] = [];');
  });

  it('should skip index.ts itself when scanning', () => {
    // Write an existing index.ts (should be ignored)
    fs.writeFileSync(
      path.join(tempDir, 'index.ts'),
      `// old content\nexport const OldSchema = {};\n`,
      'utf-8',
    );

    fs.writeFileSync(
      path.join(tempDir, 'foo.ts'),
      `export const FooSchema = withDefaults({ type: 'foo', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    // Should only have FooSchema, not OldSchema
    expect(output).toContain('FooSchema');
    expect(output).not.toContain('OldSchema');
  });

  it('should skip non-ts files', () => {
    fs.writeFileSync(
      path.join(tempDir, 'readme.md'),
      `export const ReadmeSchema = {};`,
      'utf-8',
    );

    fs.writeFileSync(
      path.join(tempDir, 'foo.ts'),
      `export const FooSchema = withDefaults({ type: 'foo', fields: [] });
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    expect(output).not.toContain('ReadmeSchema');
    expect(output).toContain('FooSchema');
  });

  it('should sort imports by relative path for deterministic output', () => {
    fs.writeFileSync(
      path.join(tempDir, 'zebra.ts'),
      `export const ZebraSchema = withDefaults({ type: 'zebra', fields: [] });`,
      'utf-8',
    );

    fs.writeFileSync(
      path.join(tempDir, 'alpha.ts'),
      `export const AlphaSchema = withDefaults({ type: 'alpha', fields: [] });`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    const alphaIdx = output.indexOf('AlphaSchema');
    const zebraIdx = output.indexOf('ZebraSchema');
    expect(alphaIdx).toBeLessThan(zebraIdx);
  });

  it('should print output but not create index.ts when --dryRun is passed', () => {
    fs.writeFileSync(
      path.join(tempDir, 'foo.ts'),
      `export const FooSchema = withDefaults({ type: 'foo', fields: [] });
`,
      'utf-8',
    );

    const stdout = execSync(
      `npx tsx "${scriptPath}" --schemasDir="${tempDir}" --dryRun`,
      { encoding: 'utf-8', cwd: path.resolve(__dirname, '..') },
    );

    // Should print the generated content to stdout
    expect(stdout).toContain('FooSchema');
    expect(stdout).toContain('[dry-run]');

    // Should NOT have created index.ts
    const indexPath = path.join(tempDir, 'index.ts');
    expect(fs.existsSync(indexPath)).toBe(false);
  });

  it('should handle multiple schemas in a single file', () => {
    fs.writeFileSync(
      path.join(tempDir, 'multi.ts'),
      `export const FirstSchema = withDefaults({ type: 'first', fields: [] });
export const SecondSchema = withDefaults({ type: 'second', fields: [] });
export const FirstExtension: Extension = { kind: 'object', name: 'first-ext', features: {} };
`,
      'utf-8',
    );

    runScript(tempDir);

    const output = fs.readFileSync(path.join(tempDir, 'index.ts'), 'utf-8');
    expect(output).toContain('import { FirstSchema, SecondSchema, FirstExtension }');
    expect(output).toContain('  FirstSchema,');
    expect(output).toContain('  SecondSchema,');
    expect(output).toContain('  FirstExtension,');
  });

  // Test gap #23: Error cases
  describe('error cases', () => {
    it('should handle empty schemas directory', () => {
      // Empty directory — no schema files at all
      const exports = scanSchemas(tempDir);
      expect(exports).toEqual([]);

      const barrel = generateBarrelFile(exports);
      expect(barrel).toContain('ALL_SCHEMAS = [');
      expect(barrel).toContain('ALL_EXTENSIONS: never[] = [];');
    });

    it('should handle schema file with no exports', () => {
      fs.writeFileSync(
        path.join(tempDir, 'empty.ts'),
        `// This file has no schema or extension exports
const x = 1;
function helper() { return x; }
`,
        'utf-8',
      );

      const exports = scanSchemas(tempDir);
      expect(exports).toEqual([]);
    });

    it('should handle schema file with syntax errors (should not crash)', () => {
      fs.writeFileSync(
        path.join(tempDir, 'broken.ts'),
        `export const BrokenSchema = withDefaults({
  type: 'broken',
  fields: [
    // syntax error - unclosed bracket
`,
        'utf-8',
      );

      // Should not throw — regex-based scanning doesn't parse TS
      const exports = scanSchemas(tempDir);
      expect(exports).toHaveLength(1);
      expect(exports[0].schemas).toContain('BrokenSchema');
    });

    it('should not match commented-out export statements', () => {
      fs.writeFileSync(
        path.join(tempDir, 'commented.ts'),
        `// export const OldSchema = withDefaults({ type: 'old', fields: [] });
export const RealSchema = withDefaults({ type: 'real', fields: [] });
`,
        'utf-8',
      );

      const exports = scanSchemas(tempDir);
      expect(exports).toHaveLength(1);
      expect(exports[0].schemas).toContain('RealSchema');
      expect(exports[0].schemas).not.toContain('OldSchema');
    });

    it('should not match exports inside block comments', () => {
      fs.writeFileSync(
        path.join(tempDir, 'block-comment.ts'),
        `/*
export const DisabledSchema = withDefaults({ type: 'disabled', fields: [] });
*/
export const ActiveSchema = withDefaults({ type: 'active', fields: [] });
`,
        'utf-8',
      );

      const exports = scanSchemas(tempDir);
      expect(exports).toHaveLength(1);
      expect(exports[0].schemas).toContain('ActiveSchema');
      expect(exports[0].schemas).not.toContain('DisabledSchema');
    });
  });
});
