name: Frontend Admin Composition Analysis

on:
  pull_request:
    paths:
      - 'Dockerfile_frontend'
      - 'frontend-angular/**'
      - '.github/workflows/fe-admin-composition-analysis.yml'
    branches:
      - master
  push:
    paths:
      - 'Dockerfile_frontend'
      - 'frontend-angular/**'
      - '.github/workflows/fe-admin-composition-analysis.yml'
    branches:
      - master

jobs:
  npm_audit_scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - uses: rwjblue/setup-volta@v1
      - name: install dependencies via npm
        working-directory: ./frontend-angular
        run: npm install
      - name: npm audit
        working-directory: ./frontend-angular
        run: npm audit
