name: Frontend Angular tests

on:
  pull_request:
    paths:
      - 'Dockerfile_frontend'
      - 'frontend-angular/**'
      - '.github/workflows/frontend-admin-test.yml'

jobs:
  test:
    name: Frontend Angular tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable
      - name: Install dependencies
        working-directory: ./frontend-angular
        run: npm install
      - name: Run tests
        working-directory: ./frontend-angular
        run: npm test
