name: Frontend Application tests

on:
  pull_request:
    paths:
      - 'Dockerfile_frontend'
      - 'frontend/**'
      - '.github/workflows/frontend-app-test.yml'

jobs:
  test:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rwjblue/setup-volta@v1
      - uses: H1D/actions-ember-testing@8ca8da615c2db5889b7fbd3834e4093706754435
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Lint *.js files
        working-directory: ./frontend
        run: yarn lint:js
      - name: Lint *.hbs files
        working-directory: ./frontend
        run: yarn lint:hbs
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
      - name: Run test deploy
        working-directory: ./frontend
        run: node node_modules/ember-cli/bin/ember deploy production

  coverage:
    name: Test coverage changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
      - uses: H1D/actions-ember-testing@8ca8da615c2db5889b7fbd3834e4093706754435
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install
      - uses: mydea/ember-cli-code-coverage-action@e4130abc6c57d272d9d123870c26b8c284128adc
        with:
          working-directory: ./frontend
          test-command: "yarn test:coverage"
          coverage-file: "./frontend/coverage/coverage-summary.json"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "Frontend test coverage: {testCoverage}%"

#  build:
#    name: App build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2-beta
#        with:
#          fetch-depth: 0
#      - name: Change dir to frontend
#        run: cd frontend
#      - uses: simplabs/ember-asset-size-action@v1
#        with:
#          working-directory: ./frontend
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"