name: Test Self Hosted Runner

on: push

jobs:
  redeploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: add s3 key
        run: echo S3_KEY > aws-key.properties
      - name: Redeploy application
        run: |
          ls -l
          docker-compose -f docker-compose-run.yml pull
          docker-compose -f docker-compose-run.yml up -d --no-deps brn
          docker-compose -f docker-compose-run.yml up -d --no-deps brn_fe
          docker image prune -af