name: Test deploy on vscale.io
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: test remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VSCALE_HOST }}
        username: ${{ secrets.VSCALE_USERNAME }}
        key: ${{ secrets.VSCALE_KEY }}
        script_stop: true
        script: |
          docker ps -a
          docker-compose pull
          docker-compose up -d --no-deps brn
          docker-compose up -d --no-deps brn_fe
          docker image prune -af