name: Test Self Hosted Runner

on: push

jobs:
  redeploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: add s3 key
        run: echo S3_KEY > aws-key.properties
      - name: Redeploy application
        run: |
          ls -l
          docker-compose pull -f docker-compose-run.yml
          docker-compose up -d --no-deps brn -f docker-compose-run.yml
          docker-compose up -d --no-deps brn_fe -f docker-compose-run.yml
          docker image prune -af