name: Test Self Hosted Runner

on: push

jobs:
  redeploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: add s3 key
        run: echo S3_KEY > aws-key.properties
      - name: Redeploy application
        run: |
          mv docker-compose-run.yml docker-compose.yml
          docker-compose pull
          docker-compose up -d --no-deps brn
          docker-compose up -d --no-deps brn_fe
          docker image prune -af