name: vscale redeploy

on:
  push:
    branches:
      - EPMLABSBRN-543

jobs:
  redeploy_vscaleio_instance:
    runs-on: vscale
    steps:
      - uses: actions/checkout@master
      - name: add s3 key
        run: echo "$S3_KEY"|base64 -d > aws-key.properties
        env:
          S3_KEY: ${{ secrets.S3_KEY }}
          YANDEX_AUTH_TOKEN: ${{ secrets.YANDEX_AUTH_TOKEN }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
      - name: Redeploy application
        run: |
          mv docker-compose-run.yml docker-compose.yml
          sed -i -e 's/_YANDEX_AUTH_TOKEN_/$YANDEX_AUTH_TOKEN/' docker-compose.yml
          sed -i -e 's/_YANDEX_FOLDER_ID_/$YANDEX_FOLDER_ID/' docker-compose.yml
          docker-compose pull
          docker-compose up -d --no-deps brn
          docker-compose up -d --no-deps brn_fe
          docker image prune -af
